name: Release Service

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: k0gen/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v3

      - name: Build the service package
        run: |
          git submodule update --init --recursive
          start-sdk init
          make
          mv ${PACKAGE_ID}*s9pk ~/
        shell: bash
        id: build
        env:
          PACKAGE_ID: $(yq e ".id" manifest.yaml)
          PACKAGE_TITLE: $(yq e ".title" manifest.yaml)

      - name: Generate sha256 checksum
        run: |
          sha256sum ${PACKAGE_ID}.s9pk > ${PACKAGE_ID}.s9pk.sha256
        shell: bash

      - name: Generate changelog
        run: |
          echo "## What's Changed" > change-log.txt
          yq e '.release-notes' manifest.yaml >> change-log.txt
          echo "## SHA256 Hash" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum ${PACKAGE_ID}.s9pk >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.PACKAGE_TITLE }} ${{ github.ref_name }}
          body_path: change-log.txt
          files: |
            ${PACKAGE_ID}.s9pk
            ${PACKAGE_ID}.s9pk.sha256
